<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<eagle version="9.6.2">
<drawing>
<settings>
<setting alwaysvectorfont="no"/>
<setting verticaltext="up"/>
</settings>
<grid distance="0.1" unitdist="inch" unit="inch" style="lines" multiple="1" display="no" altdistance="0.01" altunitdist="inch" altunit="inch"/>
<layers>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="no" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/>
</layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R">
<libraries>
<library name="D2K">
<description>&lt;b&gt;D2K V1 modules&lt;/b&gt;&lt;br&gt;Raspberry Pi 5, Active Cooler, Waveshare 5inch HDMI LCD (H), Waveshare 4-DSI-TOUCH-A, 27 W USB-C PSU. Symbol-only devices for the system interconnect schematic. Generated by gen_d2k_lbr.py.</description>
<packages>
</packages>
<symbols>
<symbol name="RPI5_USBC_PWR">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-12.7" width="0.254" layer="94"/>
<wire x1="20.32" y1="-12.7" x2="0" y2="-12.7" width="0.254" layer="94"/>
<wire x1="0" y1="-12.7" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-15.24" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">USB-C power in</text>
<pin name="VBUS" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">A4</text>
<pin name="CC1" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">A5</text>
<pin name="GND" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">A1</text>
<pin name="CC2" x="-5.08" y="-10.16" length="middle" direction="pas"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">B5</text>
</symbol>
<symbol name="HDMI_D">
<wire x1="0" y1="2.54" x2="25.4" y2="2.54" width="0.254" layer="94"/>
<wire x1="25.4" y1="2.54" x2="25.4" y2="-50.8" width="0.254" layer="94"/>
<wire x1="25.4" y1="-50.8" x2="0" y2="-50.8" width="0.254" layer="94"/>
<wire x1="0" y1="-50.8" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-53.34" size="1.778" layer="96">&gt;VALUE</text>
<text x="12.7" y="0.64" size="1.27" layer="97" align="center">micro-HDMI</text>
<pin name="TMDS_D2+" x="30.48" y="-2.54" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-2.24" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="TMDS_D2_SH" x="30.48" y="-5.08" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-4.78" size="1.016" layer="97" align="bottom-center">4</text>
<pin name="TMDS_D2-" x="30.48" y="-7.62" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-7.32" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="TMDS_D1+" x="30.48" y="-10.16" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-9.86" size="1.016" layer="97" align="bottom-center">6</text>
<pin name="TMDS_D1_SH" x="30.48" y="-12.7" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-12.4" size="1.016" layer="97" align="bottom-center">7</text>
<pin name="TMDS_D1-" x="30.48" y="-15.24" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-14.94" size="1.016" layer="97" align="bottom-center">8</text>
<pin name="TMDS_D0+" x="30.48" y="-17.78" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-17.48" size="1.016" layer="97" align="bottom-center">9</text>
<pin name="TMDS_D0_SH" x="30.48" y="-20.32" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-20.02" size="1.016" layer="97" align="bottom-center">10</text>
<pin name="TMDS_D0-" x="30.48" y="-22.86" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-22.56" size="1.016" layer="97" align="bottom-center">11</text>
<pin name="TMDS_CLK+" x="30.48" y="-25.4" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-25.1" size="1.016" layer="97" align="bottom-center">12</text>
<pin name="TMDS_CLK_SH" x="30.48" y="-27.94" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-27.64" size="1.016" layer="97" align="bottom-center">13</text>
<pin name="TMDS_CLK-" x="30.48" y="-30.48" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-30.18" size="1.016" layer="97" align="bottom-center">14</text>
<pin name="CEC" x="30.48" y="-33.02" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-32.72" size="1.016" layer="97" align="bottom-center">15</text>
<pin name="UTILITY" x="30.48" y="-35.56" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-35.26" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="DDC_SCL" x="30.48" y="-38.1" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-37.8" size="1.016" layer="97" align="bottom-center">17</text>
<pin name="DDC_SDA" x="30.48" y="-40.64" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-40.34" size="1.016" layer="97" align="bottom-center">18</text>
<pin name="DDC_GND" x="30.48" y="-43.18" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-42.88" size="1.016" layer="97" align="bottom-center">16</text>
<pin name="+5V" x="30.48" y="-45.72" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-45.42" size="1.016" layer="97" align="bottom-center">19</text>
<pin name="HPD" x="30.48" y="-48.26" length="middle" direction="pas" rot="R180"/>
<text x="27.94" y="-47.96" size="1.016" layer="97" align="bottom-center">1</text>
</symbol>
<symbol name="MIPI_22">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-58.42" width="0.254" layer="94"/>
<wire x1="20.32" y1="-58.42" x2="0" y2="-58.42" width="0.254" layer="94"/>
<wire x1="0" y1="-58.42" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-60.96" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">CAM/DISP 22p</text>
<pin name="GND@1" x="25.4" y="-2.54" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="D0_N" x="25.4" y="-5.08" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="D0_P" x="25.4" y="-7.62" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="GND@2" x="25.4" y="-10.16" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
<pin name="D1_N" x="25.4" y="-12.7" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-12.4" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="D1_P" x="25.4" y="-15.24" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-14.94" size="1.016" layer="97" align="bottom-center">6</text>
<pin name="GND@3" x="25.4" y="-17.78" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-17.48" size="1.016" layer="97" align="bottom-center">7</text>
<pin name="CLK_N" x="25.4" y="-20.32" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-20.02" size="1.016" layer="97" align="bottom-center">8</text>
<pin name="CLK_P" x="25.4" y="-22.86" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-22.56" size="1.016" layer="97" align="bottom-center">9</text>
<pin name="GND@4" x="25.4" y="-25.4" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-25.1" size="1.016" layer="97" align="bottom-center">10</text>
<pin name="D2_N" x="25.4" y="-27.94" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-27.64" size="1.016" layer="97" align="bottom-center">11</text>
<pin name="D2_P" x="25.4" y="-30.48" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-30.18" size="1.016" layer="97" align="bottom-center">12</text>
<pin name="GND@5" x="25.4" y="-33.02" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-32.72" size="1.016" layer="97" align="bottom-center">13</text>
<pin name="D3_N" x="25.4" y="-35.56" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-35.26" size="1.016" layer="97" align="bottom-center">14</text>
<pin name="D3_P" x="25.4" y="-38.1" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-37.8" size="1.016" layer="97" align="bottom-center">15</text>
<pin name="GND@6" x="25.4" y="-40.64" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-40.34" size="1.016" layer="97" align="bottom-center">16</text>
<pin name="IO0" x="25.4" y="-43.18" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-42.88" size="1.016" layer="97" align="bottom-center">17</text>
<pin name="IO1" x="25.4" y="-45.72" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-45.42" size="1.016" layer="97" align="bottom-center">18</text>
<pin name="GND@7" x="25.4" y="-48.26" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-47.96" size="1.016" layer="97" align="bottom-center">19</text>
<pin name="SCL" x="25.4" y="-50.8" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-50.5" size="1.016" layer="97" align="bottom-center">20</text>
<pin name="SDA" x="25.4" y="-53.34" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-53.04" size="1.016" layer="97" align="bottom-center">21</text>
<pin name="3V3" x="25.4" y="-55.88" length="middle" direction="pwr" rot="R180"/>
<text x="22.86" y="-55.58" size="1.016" layer="97" align="bottom-center">22</text>
</symbol>
<symbol name="RPI_GPIO_40">
<wire x1="0" y1="2.54" x2="55.88" y2="2.54" width="0.254" layer="94"/>
<wire x1="55.88" y1="2.54" x2="55.88" y2="-53.34" width="0.254" layer="94"/>
<wire x1="55.88" y1="-53.34" x2="0" y2="-53.34" width="0.254" layer="94"/>
<wire x1="0" y1="-53.34" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-55.88" size="1.778" layer="96">&gt;VALUE</text>
<text x="27.94" y="0.64" size="1.27" layer="97" align="center">40-pin header</text>
<pin name="3V3@1" x="-5.08" y="-2.54" length="middle" direction="pwr"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="GPIO2_SDA1" x="-5.08" y="-5.08" length="middle" direction="io"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="GPIO3_SCL1" x="-5.08" y="-7.62" length="middle" direction="io"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="GPIO4" x="-5.08" y="-10.16" length="middle" direction="io"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">7</text>
<pin name="GND@2" x="-5.08" y="-12.7" length="middle" direction="pwr"/>
<text x="-2.54" y="-12.4" size="1.016" layer="97" align="bottom-center">9</text>
<pin name="GPIO17" x="-5.08" y="-15.24" length="middle" direction="io"/>
<text x="-2.54" y="-14.94" size="1.016" layer="97" align="bottom-center">11</text>
<pin name="GPIO27" x="-5.08" y="-17.78" length="middle" direction="io"/>
<text x="-2.54" y="-17.48" size="1.016" layer="97" align="bottom-center">13</text>
<pin name="GPIO22" x="-5.08" y="-20.32" length="middle" direction="io"/>
<text x="-2.54" y="-20.02" size="1.016" layer="97" align="bottom-center">15</text>
<pin name="3V3@2" x="-5.08" y="-22.86" length="middle" direction="pwr"/>
<text x="-2.54" y="-22.56" size="1.016" layer="97" align="bottom-center">17</text>
<pin name="GPIO10_MOSI" x="-5.08" y="-25.4" length="middle" direction="io"/>
<text x="-2.54" y="-25.1" size="1.016" layer="97" align="bottom-center">19</text>
<pin name="GPIO9_MISO" x="-5.08" y="-27.94" length="middle" direction="io"/>
<text x="-2.54" y="-27.64" size="1.016" layer="97" align="bottom-center">21</text>
<pin name="GPIO11_SCLK" x="-5.08" y="-30.48" length="middle" direction="io"/>
<text x="-2.54" y="-30.18" size="1.016" layer="97" align="bottom-center">23</text>
<pin name="GND@5" x="-5.08" y="-33.02" length="middle" direction="pwr"/>
<text x="-2.54" y="-32.72" size="1.016" layer="97" align="bottom-center">25</text>
<pin name="ID_SD" x="-5.08" y="-35.56" length="middle" direction="io"/>
<text x="-2.54" y="-35.26" size="1.016" layer="97" align="bottom-center">27</text>
<pin name="GPIO5" x="-5.08" y="-38.1" length="middle" direction="io"/>
<text x="-2.54" y="-37.8" size="1.016" layer="97" align="bottom-center">29</text>
<pin name="GPIO6" x="-5.08" y="-40.64" length="middle" direction="io"/>
<text x="-2.54" y="-40.34" size="1.016" layer="97" align="bottom-center">31</text>
<pin name="GPIO13" x="-5.08" y="-43.18" length="middle" direction="io"/>
<text x="-2.54" y="-42.88" size="1.016" layer="97" align="bottom-center">33</text>
<pin name="GPIO19_PCM_FS" x="-5.08" y="-45.72" length="middle" direction="io"/>
<text x="-2.54" y="-45.42" size="1.016" layer="97" align="bottom-center">35</text>
<pin name="GPIO26" x="-5.08" y="-48.26" length="middle" direction="io"/>
<text x="-2.54" y="-47.96" size="1.016" layer="97" align="bottom-center">37</text>
<pin name="GND@8" x="-5.08" y="-50.8" length="middle" direction="pwr"/>
<text x="-2.54" y="-50.5" size="1.016" layer="97" align="bottom-center">39</text>
<pin name="5V@1" x="60.96" y="-2.54" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-2.24" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="5V@2" x="60.96" y="-5.08" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-4.78" size="1.016" layer="97" align="bottom-center">4</text>
<pin name="GND@1" x="60.96" y="-7.62" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-7.32" size="1.016" layer="97" align="bottom-center">6</text>
<pin name="GPIO14_TXD" x="60.96" y="-10.16" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-9.86" size="1.016" layer="97" align="bottom-center">8</text>
<pin name="GPIO15_RXD" x="60.96" y="-12.7" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-12.4" size="1.016" layer="97" align="bottom-center">10</text>
<pin name="GPIO18_PCM_CLK" x="60.96" y="-15.24" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-14.94" size="1.016" layer="97" align="bottom-center">12</text>
<pin name="GND@3" x="60.96" y="-17.78" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-17.48" size="1.016" layer="97" align="bottom-center">14</text>
<pin name="GPIO23" x="60.96" y="-20.32" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-20.02" size="1.016" layer="97" align="bottom-center">16</text>
<pin name="GPIO24" x="60.96" y="-22.86" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-22.56" size="1.016" layer="97" align="bottom-center">18</text>
<pin name="GND@4" x="60.96" y="-25.4" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-25.1" size="1.016" layer="97" align="bottom-center">20</text>
<pin name="GPIO25" x="60.96" y="-27.94" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-27.64" size="1.016" layer="97" align="bottom-center">22</text>
<pin name="GPIO8_CE0" x="60.96" y="-30.48" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-30.18" size="1.016" layer="97" align="bottom-center">24</text>
<pin name="GPIO7_CE1" x="60.96" y="-33.02" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-32.72" size="1.016" layer="97" align="bottom-center">26</text>
<pin name="ID_SC" x="60.96" y="-35.56" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-35.26" size="1.016" layer="97" align="bottom-center">28</text>
<pin name="GND@6" x="60.96" y="-38.1" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-37.8" size="1.016" layer="97" align="bottom-center">30</text>
<pin name="GPIO12" x="60.96" y="-40.64" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-40.34" size="1.016" layer="97" align="bottom-center">32</text>
<pin name="GND@7" x="60.96" y="-43.18" length="middle" direction="pwr" rot="R180"/>
<text x="58.42" y="-42.88" size="1.016" layer="97" align="bottom-center">34</text>
<pin name="GPIO16" x="60.96" y="-45.72" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-45.42" size="1.016" layer="97" align="bottom-center">36</text>
<pin name="GPIO20_PCM_DIN" x="60.96" y="-48.26" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-47.96" size="1.016" layer="97" align="bottom-center">38</text>
<pin name="GPIO21_PCM_DOUT" x="60.96" y="-50.8" length="middle" direction="io" rot="R180"/>
<text x="58.42" y="-50.5" size="1.016" layer="97" align="bottom-center">40</text>
</symbol>
<symbol name="USB2_A">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-12.7" width="0.254" layer="94"/>
<wire x1="20.32" y1="-12.7" x2="0" y2="-12.7" width="0.254" layer="94"/>
<wire x1="0" y1="-12.7" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-15.24" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">USB 2.0 A</text>
<pin name="VBUS" x="25.4" y="-2.54" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="D-" x="25.4" y="-5.08" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="D+" x="25.4" y="-7.62" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="GND" x="25.4" y="-10.16" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
</symbol>
<symbol name="USB3_A">
<wire x1="0" y1="2.54" x2="22.86" y2="2.54" width="0.254" layer="94"/>
<wire x1="22.86" y1="2.54" x2="22.86" y2="-25.4" width="0.254" layer="94"/>
<wire x1="22.86" y1="-25.4" x2="0" y2="-25.4" width="0.254" layer="94"/>
<wire x1="0" y1="-25.4" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-27.94" size="1.778" layer="96">&gt;VALUE</text>
<text x="11.43" y="0.64" size="1.27" layer="97" align="center">USB 3.0 A</text>
<pin name="VBUS" x="27.94" y="-2.54" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="D-" x="27.94" y="-5.08" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="D+" x="27.94" y="-7.62" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="GND" x="27.94" y="-10.16" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
<pin name="SSRX-" x="27.94" y="-12.7" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-12.4" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="SSRX+" x="27.94" y="-15.24" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-14.94" size="1.016" layer="97" align="bottom-center">6</text>
<pin name="GND_DRAIN" x="27.94" y="-17.78" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-17.48" size="1.016" layer="97" align="bottom-center">7</text>
<pin name="SSTX-" x="27.94" y="-20.32" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-20.02" size="1.016" layer="97" align="bottom-center">8</text>
<pin name="SSTX+" x="27.94" y="-22.86" length="middle" direction="pas" rot="R180"/>
<text x="25.4" y="-22.56" size="1.016" layer="97" align="bottom-center">9</text>
</symbol>
<symbol name="FAN_4">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-12.7" width="0.254" layer="94"/>
<wire x1="20.32" y1="-12.7" x2="0" y2="-12.7" width="0.254" layer="94"/>
<wire x1="0" y1="-12.7" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-15.24" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">Fan header JST-SH 4p</text>
<pin name="5V" x="25.4" y="-2.54" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="PWM" x="25.4" y="-5.08" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="GND" x="25.4" y="-7.62" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="TACH" x="25.4" y="-10.16" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
</symbol>
<symbol name="FAN_4_L">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-12.7" width="0.254" layer="94"/>
<wire x1="20.32" y1="-12.7" x2="0" y2="-12.7" width="0.254" layer="94"/>
<wire x1="0" y1="-12.7" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-15.24" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">Fan lead JST-SH 4p</text>
<pin name="5V" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="PWM" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="GND" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="TACH" x="-5.08" y="-10.16" length="middle" direction="pas"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
</symbol>
<symbol name="HDMI_A">
<wire x1="0" y1="2.54" x2="25.4" y2="2.54" width="0.254" layer="94"/>
<wire x1="25.4" y1="2.54" x2="25.4" y2="-50.8" width="0.254" layer="94"/>
<wire x1="25.4" y1="-50.8" x2="0" y2="-50.8" width="0.254" layer="94"/>
<wire x1="0" y1="-50.8" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-53.34" size="1.778" layer="96">&gt;VALUE</text>
<text x="12.7" y="0.64" size="1.27" layer="97" align="center">HDMI type A (Display)</text>
<pin name="TMDS_D2+" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="TMDS_D2_SH" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="TMDS_D2-" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="TMDS_D1+" x="-5.08" y="-10.16" length="middle" direction="pas"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
<pin name="TMDS_D1_SH" x="-5.08" y="-12.7" length="middle" direction="pas"/>
<text x="-2.54" y="-12.4" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="TMDS_D1-" x="-5.08" y="-15.24" length="middle" direction="pas"/>
<text x="-2.54" y="-14.94" size="1.016" layer="97" align="bottom-center">6</text>
<pin name="TMDS_D0+" x="-5.08" y="-17.78" length="middle" direction="pas"/>
<text x="-2.54" y="-17.48" size="1.016" layer="97" align="bottom-center">7</text>
<pin name="TMDS_D0_SH" x="-5.08" y="-20.32" length="middle" direction="pas"/>
<text x="-2.54" y="-20.02" size="1.016" layer="97" align="bottom-center">8</text>
<pin name="TMDS_D0-" x="-5.08" y="-22.86" length="middle" direction="pas"/>
<text x="-2.54" y="-22.56" size="1.016" layer="97" align="bottom-center">9</text>
<pin name="TMDS_CLK+" x="-5.08" y="-25.4" length="middle" direction="pas"/>
<text x="-2.54" y="-25.1" size="1.016" layer="97" align="bottom-center">10</text>
<pin name="TMDS_CLK_SH" x="-5.08" y="-27.94" length="middle" direction="pas"/>
<text x="-2.54" y="-27.64" size="1.016" layer="97" align="bottom-center">11</text>
<pin name="TMDS_CLK-" x="-5.08" y="-30.48" length="middle" direction="pas"/>
<text x="-2.54" y="-30.18" size="1.016" layer="97" align="bottom-center">12</text>
<pin name="CEC" x="-5.08" y="-33.02" length="middle" direction="pas"/>
<text x="-2.54" y="-32.72" size="1.016" layer="97" align="bottom-center">13</text>
<pin name="UTILITY" x="-5.08" y="-35.56" length="middle" direction="pas"/>
<text x="-2.54" y="-35.26" size="1.016" layer="97" align="bottom-center">14</text>
<pin name="DDC_SCL" x="-5.08" y="-38.1" length="middle" direction="pas"/>
<text x="-2.54" y="-37.8" size="1.016" layer="97" align="bottom-center">15</text>
<pin name="DDC_SDA" x="-5.08" y="-40.64" length="middle" direction="pas"/>
<text x="-2.54" y="-40.34" size="1.016" layer="97" align="bottom-center">16</text>
<pin name="DDC_GND" x="-5.08" y="-43.18" length="middle" direction="pas"/>
<text x="-2.54" y="-42.88" size="1.016" layer="97" align="bottom-center">17</text>
<pin name="+5V" x="-5.08" y="-45.72" length="middle" direction="pas"/>
<text x="-2.54" y="-45.42" size="1.016" layer="97" align="bottom-center">18</text>
<pin name="HPD" x="-5.08" y="-48.26" length="middle" direction="pas"/>
<text x="-2.54" y="-47.96" size="1.016" layer="97" align="bottom-center">19</text>
</symbol>
<symbol name="USB_MICRO_B">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-15.24" width="0.254" layer="94"/>
<wire x1="20.32" y1="-15.24" x2="0" y2="-15.24" width="0.254" layer="94"/>
<wire x1="0" y1="-15.24" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-17.78" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">micro-USB Touch</text>
<pin name="VBUS" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="D-" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="D+" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="GND" x="-5.08" y="-10.16" length="middle" direction="pas"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="ID" x="-5.08" y="-12.7" length="middle" direction="pas"/>
<text x="-2.54" y="-12.4" size="1.016" layer="97" align="bottom-center">4</text>
</symbol>
<symbol name="USB_MICRO_B_PWR">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-7.62" width="0.254" layer="94"/>
<wire x1="20.32" y1="-7.62" x2="0" y2="-7.62" width="0.254" layer="94"/>
<wire x1="0" y1="-7.62" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-10.16" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">micro-USB DC power</text>
<pin name="VBUS" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="GND" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">5</text>
</symbol>
<symbol name="AUDIO_JACK">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-10.16" width="0.254" layer="94"/>
<wire x1="20.32" y1="-10.16" x2="0" y2="-10.16" width="0.254" layer="94"/>
<wire x1="0" y1="-10.16" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-12.7" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">3.5 mm jack</text>
<pin name="L" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">T</text>
<pin name="R" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">R</text>
<pin name="GND" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">S</text>
</symbol>
<symbol name="SPK_HEADER_4">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-12.7" width="0.254" layer="94"/>
<wire x1="20.32" y1="-12.7" x2="0" y2="-12.7" width="0.254" layer="94"/>
<wire x1="0" y1="-12.7" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-15.24" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">Speaker header 4p</text>
<pin name="SPK1" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="SPK2" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="SPK3" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="SPK4" x="-5.08" y="-10.16" length="middle" direction="pas"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
</symbol>
<symbol name="MIPI_22_L">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-58.42" width="0.254" layer="94"/>
<wire x1="20.32" y1="-58.42" x2="0" y2="-58.42" width="0.254" layer="94"/>
<wire x1="0" y1="-58.42" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-60.96" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">DSI 22p 0.5 mm</text>
<pin name="GND@1" x="-5.08" y="-2.54" length="middle" direction="pwr"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="D0_N" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
<pin name="D0_P" x="-5.08" y="-7.62" length="middle" direction="pas"/>
<text x="-2.54" y="-7.32" size="1.016" layer="97" align="bottom-center">3</text>
<pin name="GND@2" x="-5.08" y="-10.16" length="middle" direction="pwr"/>
<text x="-2.54" y="-9.86" size="1.016" layer="97" align="bottom-center">4</text>
<pin name="D1_N" x="-5.08" y="-12.7" length="middle" direction="pas"/>
<text x="-2.54" y="-12.4" size="1.016" layer="97" align="bottom-center">5</text>
<pin name="D1_P" x="-5.08" y="-15.24" length="middle" direction="pas"/>
<text x="-2.54" y="-14.94" size="1.016" layer="97" align="bottom-center">6</text>
<pin name="GND@3" x="-5.08" y="-17.78" length="middle" direction="pwr"/>
<text x="-2.54" y="-17.48" size="1.016" layer="97" align="bottom-center">7</text>
<pin name="CLK_N" x="-5.08" y="-20.32" length="middle" direction="pas"/>
<text x="-2.54" y="-20.02" size="1.016" layer="97" align="bottom-center">8</text>
<pin name="CLK_P" x="-5.08" y="-22.86" length="middle" direction="pas"/>
<text x="-2.54" y="-22.56" size="1.016" layer="97" align="bottom-center">9</text>
<pin name="GND@4" x="-5.08" y="-25.4" length="middle" direction="pwr"/>
<text x="-2.54" y="-25.1" size="1.016" layer="97" align="bottom-center">10</text>
<pin name="D2_N" x="-5.08" y="-27.94" length="middle" direction="pas"/>
<text x="-2.54" y="-27.64" size="1.016" layer="97" align="bottom-center">11</text>
<pin name="D2_P" x="-5.08" y="-30.48" length="middle" direction="pas"/>
<text x="-2.54" y="-30.18" size="1.016" layer="97" align="bottom-center">12</text>
<pin name="GND@5" x="-5.08" y="-33.02" length="middle" direction="pwr"/>
<text x="-2.54" y="-32.72" size="1.016" layer="97" align="bottom-center">13</text>
<pin name="D3_N" x="-5.08" y="-35.56" length="middle" direction="pas"/>
<text x="-2.54" y="-35.26" size="1.016" layer="97" align="bottom-center">14</text>
<pin name="D3_P" x="-5.08" y="-38.1" length="middle" direction="pas"/>
<text x="-2.54" y="-37.8" size="1.016" layer="97" align="bottom-center">15</text>
<pin name="GND@6" x="-5.08" y="-40.64" length="middle" direction="pwr"/>
<text x="-2.54" y="-40.34" size="1.016" layer="97" align="bottom-center">16</text>
<pin name="IO0" x="-5.08" y="-43.18" length="middle" direction="pas"/>
<text x="-2.54" y="-42.88" size="1.016" layer="97" align="bottom-center">17</text>
<pin name="IO1" x="-5.08" y="-45.72" length="middle" direction="pas"/>
<text x="-2.54" y="-45.42" size="1.016" layer="97" align="bottom-center">18</text>
<pin name="GND@7" x="-5.08" y="-48.26" length="middle" direction="pwr"/>
<text x="-2.54" y="-47.96" size="1.016" layer="97" align="bottom-center">19</text>
<pin name="SCL" x="-5.08" y="-50.8" length="middle" direction="pas"/>
<text x="-2.54" y="-50.5" size="1.016" layer="97" align="bottom-center">20</text>
<pin name="SDA" x="-5.08" y="-53.34" length="middle" direction="pas"/>
<text x="-2.54" y="-53.04" size="1.016" layer="97" align="bottom-center">21</text>
<pin name="3V3" x="-5.08" y="-55.88" length="middle" direction="pwr"/>
<text x="-2.54" y="-55.58" size="1.016" layer="97" align="bottom-center">22</text>
</symbol>
<symbol name="PWR_2">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-7.62" width="0.254" layer="94"/>
<wire x1="20.32" y1="-7.62" x2="0" y2="-7.62" width="0.254" layer="94"/>
<wire x1="0" y1="-7.62" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-10.16" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">Power 2p</text>
<pin name="5V" x="-5.08" y="-2.54" length="middle" direction="pwr"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">1</text>
<pin name="GND" x="-5.08" y="-5.08" length="middle" direction="pwr"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">2</text>
</symbol>
<symbol name="PSU_USBC">
<wire x1="0" y1="2.54" x2="20.32" y2="2.54" width="0.254" layer="94"/>
<wire x1="20.32" y1="2.54" x2="20.32" y2="-10.16" width="0.254" layer="94"/>
<wire x1="20.32" y1="-10.16" x2="0" y2="-10.16" width="0.254" layer="94"/>
<wire x1="0" y1="-10.16" x2="0" y2="2.54" width="0.254" layer="94"/>
<text x="0" y="3.81" size="1.778" layer="95">&gt;NAME</text>
<text x="0" y="-12.7" size="1.778" layer="96">&gt;VALUE</text>
<text x="10.16" y="0.64" size="1.27" layer="97" align="center">USB-C PSU</text>
<pin name="AC_L" x="-5.08" y="-2.54" length="middle" direction="pas"/>
<text x="-2.54" y="-2.24" size="1.016" layer="97" align="bottom-center">L</text>
<pin name="AC_N" x="-5.08" y="-5.08" length="middle" direction="pas"/>
<text x="-2.54" y="-4.78" size="1.016" layer="97" align="bottom-center">N</text>
<pin name="VBUS" x="25.4" y="-2.54" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-2.24" size="1.016" layer="97" align="bottom-center">A4</text>
<pin name="CC" x="25.4" y="-5.08" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-4.78" size="1.016" layer="97" align="bottom-center">A5</text>
<pin name="GND" x="25.4" y="-7.62" length="middle" direction="pas" rot="R180"/>
<text x="22.86" y="-7.32" size="1.016" layer="97" align="bottom-center">A1</text>
</symbol>
</symbols>
<devicesets>
<deviceset name="RASPBERRY_PI_5" prefix="U" uservalue="yes">
<description>&lt;b&gt;Raspberry Pi 5 (4/8 GB). D2K V1 compute. Board 85 x 56 mm, 4x M2.5 on 58 x 49.&lt;/b&gt;&lt;br&gt;&lt;br&gt;Connector pin = signal:&lt;br&gt;&lt;b&gt;PWR&lt;/b&gt; (USB-C power in): A4=VBUS, A5=CC1, A1=GND, B5=CC2&lt;br&gt;&lt;b&gt;HDMI0&lt;/b&gt; (micro-HDMI): 3=TMDS_D2+, 4=TMDS_D2_SH, 5=TMDS_D2-, 6=TMDS_D1+, 7=TMDS_D1_SH, 8=TMDS_D1-, 9=TMDS_D0+, 10=TMDS_D0_SH, 11=TMDS_D0-, 12=TMDS_CLK+, 13=TMDS_CLK_SH, 14=TMDS_CLK-, 15=CEC, 2=UTILITY, 17=DDC_SCL, 18=DDC_SDA, 16=DDC_GND, 19=+5V, 1=HPD&lt;br&gt;&lt;b&gt;HDMI1&lt;/b&gt; (micro-HDMI): 3=TMDS_D2+, 4=TMDS_D2_SH, 5=TMDS_D2-, 6=TMDS_D1+, 7=TMDS_D1_SH, 8=TMDS_D1-, 9=TMDS_D0+, 10=TMDS_D0_SH, 11=TMDS_D0-, 12=TMDS_CLK+, 13=TMDS_CLK_SH, 14=TMDS_CLK-, 15=CEC, 2=UTILITY, 17=DDC_SCL, 18=DDC_SDA, 16=DDC_GND, 19=+5V, 1=HPD&lt;br&gt;&lt;b&gt;DISP0&lt;/b&gt; (CAM/DISP 22p): 1=GND, 2=D0_N, 3=D0_P, 4=GND, 5=D1_N, 6=D1_P, 7=GND, 8=CLK_N, 9=CLK_P, 10=GND, 11=D2_N, 12=D2_P, 13=GND, 14=D3_N, 15=D3_P, 16=GND, 17=IO0, 18=IO1, 19=GND, 20=SCL, 21=SDA, 22=3V3&lt;br&gt;&lt;b&gt;DISP1&lt;/b&gt; (CAM/DISP 22p): 1=GND, 2=D0_N, 3=D0_P, 4=GND, 5=D1_N, 6=D1_P, 7=GND, 8=CLK_N, 9=CLK_P, 10=GND, 11=D2_N, 12=D2_P, 13=GND, 14=D3_N, 15=D3_P, 16=GND, 17=IO0, 18=IO1, 19=GND, 20=SCL, 21=SDA, 22=3V3&lt;br&gt;&lt;b&gt;GPIO&lt;/b&gt; (40-pin header): 1=3V3, 2=5V, 3=GPIO2_SDA1, 4=5V, 5=GPIO3_SCL1, 6=GND, 7=GPIO4, 8=GPIO14_TXD, 9=GND, 10=GPIO15_RXD, 11=GPIO17, 12=GPIO18_PCM_CLK, 13=GPIO27, 14=GND, 15=GPIO22, 16=GPIO23, 17=3V3, 18=GPIO24, 19=GPIO10_MOSI, 20=GND, 21=GPIO9_MISO, 22=GPIO25, 23=GPIO11_SCLK, 24=GPIO8_CE0, 25=GND, 26=GPIO7_CE1, 27=ID_SD, 28=ID_SC, 29=GPIO5, 30=GND, 31=GPIO6, 32=GPIO12, 33=GPIO13, 34=GND, 35=GPIO19_PCM_FS, 36=GPIO16, 37=GPIO26, 38=GPIO20_PCM_DIN, 39=GND, 40=GPIO21_PCM_DOUT&lt;br&gt;&lt;b&gt;USB2_0&lt;/b&gt; (USB 2.0 A): 1=VBUS, 2=D-, 3=D+, 4=GND&lt;br&gt;&lt;b&gt;USB2_1&lt;/b&gt; (USB 2.0 A): 1=VBUS, 2=D-, 3=D+, 4=GND&lt;br&gt;&lt;b&gt;USB3_0&lt;/b&gt; (USB 3.0 A): 1=VBUS, 2=D-, 3=D+, 4=GND, 5=SSRX-, 6=SSRX+, 7=GND_DRAIN, 8=SSTX-, 9=SSTX+&lt;br&gt;&lt;b&gt;USB3_1&lt;/b&gt; (USB 3.0 A): 1=VBUS, 2=D-, 3=D+, 4=GND, 5=SSRX-, 6=SSRX+, 7=GND_DRAIN, 8=SSTX-, 9=SSTX+&lt;br&gt;&lt;b&gt;FAN&lt;/b&gt; (Fan header JST-SH 4p): 1=5V, 2=PWM, 3=GND, 4=TACH</description>
<gates>
<gate name="PWR" symbol="RPI5_USBC_PWR" x="0" y="0" addlevel="next"/>
<gate name="HDMI0" symbol="HDMI_D" x="50.8" y="0" addlevel="next"/>
<gate name="HDMI1" symbol="HDMI_D" x="101.6" y="0" addlevel="next"/>
<gate name="DISP0" symbol="MIPI_22" x="152.4" y="0" addlevel="next"/>
<gate name="DISP1" symbol="MIPI_22" x="203.2" y="0" addlevel="next"/>
<gate name="GPIO" symbol="RPI_GPIO_40" x="254" y="0" addlevel="next"/>
<gate name="USB2_0" symbol="USB2_A" x="304.8" y="0" addlevel="next"/>
<gate name="USB2_1" symbol="USB2_A" x="355.6" y="0" addlevel="next"/>
<gate name="USB3_0" symbol="USB3_A" x="406.4" y="0" addlevel="next"/>
<gate name="USB3_1" symbol="USB3_A" x="457.2" y="0" addlevel="next"/>
<gate name="FAN" symbol="FAN_4" x="508" y="0" addlevel="next"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""><attribute name="MANUFACTURER" value="Raspberry Pi Ltd"/><attribute name="MPN" value="Raspberry Pi 5"/><attribute name="SUPPLY" value="5.1 V USB-C PD, 5 A (27 W PSU)"/><attribute name="USB_BUDGET" value="1.6 A total on the 4 USB-A ports with a 5 A PSU, 600 mA otherwise"/><attribute name="DOC" value="https://datasheets.raspberrypi.com/rpi5/raspberry-pi-5-mechanical-drawing.pdf"/><attribute name="VERIFY" value="MIPI_22 IO0/IO1 roles and FAN pin order are from the generic RPi pinout, check before wiring"/></technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="RPI5_ACTIVE_COOLER" prefix="M" uservalue="yes">
<description>&lt;b&gt;Raspberry Pi Active Cooler for Pi 5 (SC1148). 63.5 x 42.5 x 13.7 mm, blower fan, PWM + tach, 5 V from the Pi fan header.&lt;/b&gt;&lt;br&gt;&lt;br&gt;Connector pin = signal:&lt;br&gt;&lt;b&gt;FAN&lt;/b&gt; (Fan lead JST-SH 4p): 1=5V, 2=PWM, 3=GND, 4=TACH</description>
<gates>
<gate name="FAN" symbol="FAN_4_L" x="0" y="0" addlevel="next"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""><attribute name="MANUFACTURER" value="Raspberry Pi Ltd"/><attribute name="MPN" value="SC1148"/><attribute name="SUPPLY" value="5 V from Pi FAN header"/><attribute name="DOC" value="https://pip.raspberrypi.com/documents/RP-008188-DS-raspberry-pi-active-cooler-product-brief.pdf"/></technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="WAVESHARE_5IN_HDMI_LCD_H" prefix="LCD" uservalue="yes">
<description>&lt;b&gt;Waveshare 5inch HDMI LCD (H): 800x480 TFT, 5-point capacitive USB touch, toughened glass, RTD2660 scaler. D2K upper screen. PCB/glass 121 x 76 mm, holes 109 x 84.&lt;/b&gt;&lt;br&gt;&lt;br&gt;Connector pin = signal:&lt;br&gt;&lt;b&gt;HDMI&lt;/b&gt; (HDMI type A (Display)): 1=TMDS_D2+, 2=TMDS_D2_SH, 3=TMDS_D2-, 4=TMDS_D1+, 5=TMDS_D1_SH, 6=TMDS_D1-, 7=TMDS_D0+, 8=TMDS_D0_SH, 9=TMDS_D0-, 10=TMDS_CLK+, 11=TMDS_CLK_SH, 12=TMDS_CLK-, 13=CEC, 14=UTILITY, 15=DDC_SCL, 16=DDC_SDA, 17=DDC_GND, 18=+5V, 19=HPD&lt;br&gt;&lt;b&gt;TOUCH&lt;/b&gt; (micro-USB Touch): 1=VBUS, 2=D-, 3=D+, 5=GND, 4=ID&lt;br&gt;&lt;b&gt;DC&lt;/b&gt; (micro-USB DC power): 1=VBUS, 5=GND&lt;br&gt;&lt;b&gt;AUDIO&lt;/b&gt; (3.5 mm jack): T=L, R=R, S=GND&lt;br&gt;&lt;b&gt;SPK&lt;/b&gt; (Speaker header 4p): 1=SPK1, 2=SPK2, 3=SPK3, 4=SPK4</description>
<gates>
<gate name="HDMI" symbol="HDMI_A" x="0" y="0" addlevel="next"/>
<gate name="TOUCH" symbol="USB_MICRO_B" x="50.8" y="0" addlevel="next"/>
<gate name="DC" symbol="USB_MICRO_B_PWR" x="101.6" y="0" addlevel="next"/>
<gate name="AUDIO" symbol="AUDIO_JACK" x="152.4" y="0" addlevel="next"/>
<gate name="SPK" symbol="SPK_HEADER_4" x="203.2" y="0" addlevel="next"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""><attribute name="MANUFACTURER" value="Waveshare"/><attribute name="MPN" value="5inch HDMI LCD (H)"/><attribute name="SUPPLY" value="5 V, about 400 mA, from DC micro-USB or the Touch micro-USB"/><attribute name="TOUCH" value="USB HID, 5-point capacitive"/><attribute name="RESOLUTION" value="800x480 @ 60 Hz"/><attribute name="AUDIO" value="HDMI audio to 3.5 mm jack and 4-pin speaker header"/><attribute name="DOC" value="https://www.waveshare.com/wiki/5inch_HDMI_LCD_(H)"/><attribute name="VERIFY" value="Speaker header pin order not published: identify L/R before wiring speakers"/></technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="WAVESHARE_4_DSI_TOUCH_A" prefix="LCD" uservalue="yes">
<description>&lt;b&gt;Waveshare 4-DSI-TOUCH-A (SKU 34354): 4inch IPS 480x800 (landscape 800x480), MIPI DSI, 5-point capacitive touch, optical bonding, aluminium back. D2K lower touch screen. Outline 108.3 x 65.1 x 5.8 mm, AA 86.4 x 51.84, 8x M2.5 (corners 100 x 56, Pi pattern 58 x 49).&lt;/b&gt;&lt;br&gt;&lt;br&gt;Connector pin = signal:&lt;br&gt;&lt;b&gt;DSI&lt;/b&gt; (DSI 22p 0.5 mm): 1=GND, 2=D0_N, 3=D0_P, 4=GND, 5=D1_N, 6=D1_P, 7=GND, 8=CLK_N, 9=CLK_P, 10=GND, 11=D2_N, 12=D2_P, 13=GND, 14=D3_N, 15=D3_P, 16=GND, 17=IO0, 18=IO1, 19=GND, 20=SCL, 21=SDA, 22=3V3&lt;br&gt;&lt;b&gt;PWR&lt;/b&gt; (Power 2p): 1=5V, 2=GND</description>
<gates>
<gate name="DSI" symbol="MIPI_22_L" x="0" y="0" addlevel="next"/>
<gate name="PWR" symbol="PWR_2" x="50.8" y="0" addlevel="next"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""><attribute name="MANUFACTURER" value="Waveshare"/><attribute name="MPN" value="4-DSI-TOUCH-A"/><attribute name="SKU" value="34354"/><attribute name="SUPPLY" value="4.75-5.25 V, 180 mA typ, via 2-wire lead to Pi GPIO 5V/GND"/><attribute name="TOUCH" value="Goodix, I2C 0x14 on the DSI cable I2C (i2c-10 on Pi 5)"/><attribute name="OVERLAY" value="dtoverlay=vc4-kms-dsi-waveshare-panel-v2,4_0_inch_a (add ,dsi0 on DISP0)"/><attribute name="CABLE" value="FFC 22-pin 0.5 mm 200 mm reverse (supplied)"/><attribute name="DOC" value="https://www.waveshare.com/4-dsi-touch-a.htm"/></technology>
</technologies>
</device>
</devices>
</deviceset>
<deviceset name="PSU_USBC_27W" prefix="PS" uservalue="yes">
<description>&lt;b&gt;Raspberry Pi 27 W USB-C power supply (mains). V1 bench power: 5.1 V 5 A, PD 9 V 3 A / 12 V 2.25 A / 15 V 1.8 A.&lt;/b&gt;&lt;br&gt;&lt;br&gt;Connector pin = signal:&lt;br&gt;&lt;b&gt;P&lt;/b&gt; (USB-C PSU): L=AC_L, N=AC_N, A4=VBUS, A5=CC, A1=GND</description>
<gates>
<gate name="P" symbol="PSU_USBC" x="0" y="0" addlevel="next"/>
</gates>
<devices>
<device name="">
<technologies>
<technology name=""><attribute name="MANUFACTURER" value="Raspberry Pi Ltd"/><attribute name="MPN" value="27W USB-C PSU"/><attribute name="INPUT" value="100-240 V AC"/><attribute name="OUTPUT" value="5.1 V 5 A (PD)"/></technology>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
</libraries>
<attributes>
</attributes>
<variantdefs>
</variantdefs>
<classes>
<class number="0" name="default" width="0" drill="0">
</class>
</classes>
<parts>
<part name="PS1" library="D2K" deviceset="PSU_USBC_27W" device="" value="RPi 27W USB-C PSU"/>
<part name="U1" library="D2K" deviceset="RASPBERRY_PI_5" device="" value="Raspberry Pi 5"/>
<part name="M1" library="D2K" deviceset="RPI5_ACTIVE_COOLER" device="" value="Active Cooler SC1148"/>
<part name="LCD1" library="D2K" deviceset="WAVESHARE_5IN_HDMI_LCD_H" device="" value="5inch HDMI LCD (H) - upper"/>
<part name="LCD2" library="D2K" deviceset="WAVESHARE_4_DSI_TOUCH_A" device="" value="4-DSI-TOUCH-A - lower touch"/>
</parts>
<sheets>
<sheet>
<plain>
<text x="50.8" y="3.81" size="1.778" layer="97" align="bottom-center">W1  USB-C cable (PSU captive), 5.1 V 5 A PD</text>
<text x="-12.7" y="3.81" size="1.778" layer="97" align="bottom-center">230 V AC mains</text>
<text x="137.16" y="-24.13" size="1.778" layer="97" align="bottom-center">W2  micro-HDMI (D) -&gt; HDMI (A) cable: video 800x480 + HDMI audio</text>
<text x="134.62" y="-90.17" size="1.778" layer="97" align="bottom-center">W3  USB-A -&gt; micro-USB DATA cable: touch (USB HID) + screen power ~400 mA</text>
<text x="154.94" y="-123.19" size="1.778" layer="97" align="bottom-right">Headset (V1 sound = HDMI audio)</text>
<text x="279.4" y="3.81" size="1.778" layer="97" align="bottom-center">W4  FFC 22-pin 0.5 mm 200 mm REVERSE (supplied): DSI + touch I2C + 3V3</text>
<text x="314.96" y="-69.85" size="1.778" layer="97" align="bottom-center">W5  2-wire lead: red = 5V (pin 4), black = GND (pin 6)</text>
<text x="320.04" y="-128.27" size="1.778" layer="97" align="top-center">! GPIO 5V is not fused: one pin off can kill the Pi. Power off before plugging.</text>
<text x="279.4" y="-138.43" size="1.778" layer="97" align="bottom-center">W6  Fan lead JST-SH 4p (captive)</text>
<wire x1="-45.72" y1="40.64" x2="369.88" y2="40.64" width="0.4064" layer="94"/>
<wire x1="369.88" y1="40.64" x2="369.88" y2="-185.42" width="0.4064" layer="94"/>
<wire x1="369.88" y1="-185.42" x2="-45.72" y2="-185.42" width="0.4064" layer="94"/>
<wire x1="-45.72" y1="-185.42" x2="-45.72" y2="40.64" width="0.4064" layer="94"/>
<text x="-40.64" y="33.02" size="3.81" layer="94">D2K V1 - bench interconnect</text>
<text x="-40.64" y="26.67" size="1.778" layer="97">Raspberry Pi 5 on mains USB-C + Waveshare 5inch HDMI LCD (H) upper + Waveshare 4-DSI-TOUCH-A lower touch</text>
<text x="-40.64" y="-175.26" size="1.27" layer="97">Generated by fusion/electronics/gen_d2k_v1_sch.py - warnings and cable details: fusion/wiring.md</text>
<text x="-40.64" y="-180.34" size="1.27" layer="97">Unused: Pi HDMI1, DISP0, USB2_1, USB3, Ethernet; 5in DC micro-USB, VGA, speaker header.</text>
</plain>
<instances>
<instance part="PS1" gate="P" x="0" y="0"/>
<instance part="U1" gate="PWR" x="81.28" y="0"/>
<instance part="U1" gate="HDMI0" x="81.28" y="-27.94"/>
<instance part="LCD1" gate="HDMI" x="167.64" y="-27.94"/>
<instance part="U1" gate="USB2_0" x="81.28" y="-93.98"/>
<instance part="LCD1" gate="TOUCH" x="167.64" y="-93.98"/>
<instance part="LCD1" gate="AUDIO" x="167.64" y="-127"/>
<instance part="U1" gate="DISP1" x="228.6" y="0"/>
<instance part="LCD2" gate="DSI" x="309.88" y="0"/>
<instance part="U1" gate="GPIO" x="228.6" y="-73.66"/>
<instance part="LCD2" gate="PWR" x="345.44" y="-76.2"/>
<instance part="U1" gate="FAN" x="228.6" y="-142.24"/>
<instance part="M1" gate="FAN" x="309.88" y="-142.24"/>
</instances>
<busses>
</busses>
<nets>
<net name="VBUS_5V1" class="0">
<segment>
<pinref part="PS1" gate="P" pin="VBUS"/>
<pinref part="U1" gate="PWR" pin="VBUS"/>
<wire x1="25.4" y1="-2.54" x2="76.2" y2="-2.54" width="0.1524" layer="91"/>
</segment>
</net>
<net name="USBC_CC" class="0">
<segment>
<pinref part="PS1" gate="P" pin="CC"/>
<pinref part="U1" gate="PWR" pin="CC1"/>
<wire x1="25.4" y1="-5.08" x2="76.2" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="GND" class="0">
<segment>
<pinref part="PS1" gate="P" pin="GND"/>
<pinref part="U1" gate="PWR" pin="GND"/>
<wire x1="25.4" y1="-7.62" x2="76.2" y2="-7.62" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D2_SH"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D2_SH"/>
<wire x1="111.76" y1="-33.02" x2="162.56" y2="-33.02" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D1_SH"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D1_SH"/>
<wire x1="111.76" y1="-40.64" x2="162.56" y2="-40.64" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D0_SH"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D0_SH"/>
<wire x1="111.76" y1="-48.26" x2="162.56" y2="-48.26" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_CLK_SH"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_CLK_SH"/>
<wire x1="111.76" y1="-55.88" x2="162.56" y2="-55.88" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="HDMI0" pin="DDC_GND"/>
<pinref part="LCD1" gate="HDMI" pin="DDC_GND"/>
<wire x1="111.76" y1="-71.12" x2="162.56" y2="-71.12" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="USB2_0" pin="GND"/>
<pinref part="LCD1" gate="TOUCH" pin="GND"/>
<wire x1="106.68" y1="-104.14" x2="162.56" y2="-104.14" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@1"/>
<pinref part="LCD2" gate="DSI" pin="GND@1"/>
<wire x1="254" y1="-2.54" x2="304.8" y2="-2.54" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@2"/>
<pinref part="LCD2" gate="DSI" pin="GND@2"/>
<wire x1="254" y1="-10.16" x2="304.8" y2="-10.16" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@3"/>
<pinref part="LCD2" gate="DSI" pin="GND@3"/>
<wire x1="254" y1="-17.78" x2="304.8" y2="-17.78" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@4"/>
<pinref part="LCD2" gate="DSI" pin="GND@4"/>
<wire x1="254" y1="-25.4" x2="304.8" y2="-25.4" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@5"/>
<pinref part="LCD2" gate="DSI" pin="GND@5"/>
<wire x1="254" y1="-33.02" x2="304.8" y2="-33.02" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@6"/>
<pinref part="LCD2" gate="DSI" pin="GND@6"/>
<wire x1="254" y1="-40.64" x2="304.8" y2="-40.64" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="DISP1" pin="GND@7"/>
<pinref part="LCD2" gate="DSI" pin="GND@7"/>
<wire x1="254" y1="-48.26" x2="304.8" y2="-48.26" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="GPIO" pin="GND@1"/>
<pinref part="LCD2" gate="PWR" pin="GND"/>
<wire x1="289.56" y1="-81.28" x2="340.36" y2="-81.28" width="0.1524" layer="91"/>
</segment>
<segment>
<pinref part="U1" gate="FAN" pin="GND"/>
<pinref part="M1" gate="FAN" pin="GND"/>
<wire x1="254" y1="-149.86" x2="304.8" y2="-149.86" width="0.1524" layer="91"/>
</segment>
</net>
<net name="AC_L" class="0">
<segment>
<pinref part="PS1" gate="P" pin="AC_L"/>
<wire x1="-5.08" y1="-2.54" x2="-12.7" y2="-2.54" width="0.1524" layer="91"/>
<label x="-12.7" y="-2.54" size="1.778" layer="95" rot="R180"/>
</segment>
</net>
<net name="AC_N" class="0">
<segment>
<pinref part="PS1" gate="P" pin="AC_N"/>
<wire x1="-5.08" y1="-5.08" x2="-12.7" y2="-5.08" width="0.1524" layer="91"/>
<label x="-12.7" y="-5.08" size="1.778" layer="95" rot="R180"/>
</segment>
</net>
<net name="HDMI0_TMDS_D2+" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D2+"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D2+"/>
<wire x1="111.76" y1="-30.48" x2="162.56" y2="-30.48" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_D2-" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D2-"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D2-"/>
<wire x1="111.76" y1="-35.56" x2="162.56" y2="-35.56" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_D1+" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D1+"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D1+"/>
<wire x1="111.76" y1="-38.1" x2="162.56" y2="-38.1" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_D1-" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D1-"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D1-"/>
<wire x1="111.76" y1="-43.18" x2="162.56" y2="-43.18" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_D0+" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D0+"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D0+"/>
<wire x1="111.76" y1="-45.72" x2="162.56" y2="-45.72" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_D0-" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_D0-"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_D0-"/>
<wire x1="111.76" y1="-50.8" x2="162.56" y2="-50.8" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_CLK+" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_CLK+"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_CLK+"/>
<wire x1="111.76" y1="-53.34" x2="162.56" y2="-53.34" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_TMDS_CLK-" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="TMDS_CLK-"/>
<pinref part="LCD1" gate="HDMI" pin="TMDS_CLK-"/>
<wire x1="111.76" y1="-58.42" x2="162.56" y2="-58.42" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_CEC" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="CEC"/>
<pinref part="LCD1" gate="HDMI" pin="CEC"/>
<wire x1="111.76" y1="-60.96" x2="162.56" y2="-60.96" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_UTILITY" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="UTILITY"/>
<pinref part="LCD1" gate="HDMI" pin="UTILITY"/>
<wire x1="111.76" y1="-63.5" x2="162.56" y2="-63.5" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_DDC_SCL" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="DDC_SCL"/>
<pinref part="LCD1" gate="HDMI" pin="DDC_SCL"/>
<wire x1="111.76" y1="-66.04" x2="162.56" y2="-66.04" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_DDC_SDA" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="DDC_SDA"/>
<pinref part="LCD1" gate="HDMI" pin="DDC_SDA"/>
<wire x1="111.76" y1="-68.58" x2="162.56" y2="-68.58" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_+5V" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="+5V"/>
<pinref part="LCD1" gate="HDMI" pin="+5V"/>
<wire x1="111.76" y1="-73.66" x2="162.56" y2="-73.66" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HDMI0_HPD" class="0">
<segment>
<pinref part="U1" gate="HDMI0" pin="HPD"/>
<pinref part="LCD1" gate="HDMI" pin="HPD"/>
<wire x1="111.76" y1="-76.2" x2="162.56" y2="-76.2" width="0.1524" layer="91"/>
</segment>
</net>
<net name="USB2_0_VBUS" class="0">
<segment>
<pinref part="U1" gate="USB2_0" pin="VBUS"/>
<pinref part="LCD1" gate="TOUCH" pin="VBUS"/>
<wire x1="106.68" y1="-96.52" x2="162.56" y2="-96.52" width="0.1524" layer="91"/>
</segment>
</net>
<net name="USB2_0_D-" class="0">
<segment>
<pinref part="U1" gate="USB2_0" pin="D-"/>
<pinref part="LCD1" gate="TOUCH" pin="D-"/>
<wire x1="106.68" y1="-99.06" x2="162.56" y2="-99.06" width="0.1524" layer="91"/>
</segment>
</net>
<net name="USB2_0_D+" class="0">
<segment>
<pinref part="U1" gate="USB2_0" pin="D+"/>
<pinref part="LCD1" gate="TOUCH" pin="D+"/>
<wire x1="106.68" y1="-101.6" x2="162.56" y2="-101.6" width="0.1524" layer="91"/>
</segment>
</net>
<net name="HEADSET_L" class="0">
<segment>
<pinref part="LCD1" gate="AUDIO" pin="L"/>
<wire x1="162.56" y1="-129.54" x2="154.94" y2="-129.54" width="0.1524" layer="91"/>
<label x="154.94" y="-129.54" size="1.778" layer="95" rot="R180"/>
</segment>
</net>
<net name="HEADSET_R" class="0">
<segment>
<pinref part="LCD1" gate="AUDIO" pin="R"/>
<wire x1="162.56" y1="-132.08" x2="154.94" y2="-132.08" width="0.1524" layer="91"/>
<label x="154.94" y="-132.08" size="1.778" layer="95" rot="R180"/>
</segment>
</net>
<net name="HEADSET_GND" class="0">
<segment>
<pinref part="LCD1" gate="AUDIO" pin="GND"/>
<wire x1="162.56" y1="-134.62" x2="154.94" y2="-134.62" width="0.1524" layer="91"/>
<label x="154.94" y="-134.62" size="1.778" layer="95" rot="R180"/>
</segment>
</net>
<net name="DSI1_D0_N" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D0_N"/>
<pinref part="LCD2" gate="DSI" pin="D0_N"/>
<wire x1="254" y1="-5.08" x2="304.8" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D0_P" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D0_P"/>
<pinref part="LCD2" gate="DSI" pin="D0_P"/>
<wire x1="254" y1="-7.62" x2="304.8" y2="-7.62" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D1_N" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D1_N"/>
<pinref part="LCD2" gate="DSI" pin="D1_N"/>
<wire x1="254" y1="-12.7" x2="304.8" y2="-12.7" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D1_P" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D1_P"/>
<pinref part="LCD2" gate="DSI" pin="D1_P"/>
<wire x1="254" y1="-15.24" x2="304.8" y2="-15.24" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_CLK_N" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="CLK_N"/>
<pinref part="LCD2" gate="DSI" pin="CLK_N"/>
<wire x1="254" y1="-20.32" x2="304.8" y2="-20.32" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_CLK_P" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="CLK_P"/>
<pinref part="LCD2" gate="DSI" pin="CLK_P"/>
<wire x1="254" y1="-22.86" x2="304.8" y2="-22.86" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D2_N" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D2_N"/>
<pinref part="LCD2" gate="DSI" pin="D2_N"/>
<wire x1="254" y1="-27.94" x2="304.8" y2="-27.94" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D2_P" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D2_P"/>
<pinref part="LCD2" gate="DSI" pin="D2_P"/>
<wire x1="254" y1="-30.48" x2="304.8" y2="-30.48" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D3_N" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D3_N"/>
<pinref part="LCD2" gate="DSI" pin="D3_N"/>
<wire x1="254" y1="-35.56" x2="304.8" y2="-35.56" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_D3_P" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="D3_P"/>
<pinref part="LCD2" gate="DSI" pin="D3_P"/>
<wire x1="254" y1="-38.1" x2="304.8" y2="-38.1" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_IO0" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="IO0"/>
<pinref part="LCD2" gate="DSI" pin="IO0"/>
<wire x1="254" y1="-43.18" x2="304.8" y2="-43.18" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_IO1" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="IO1"/>
<pinref part="LCD2" gate="DSI" pin="IO1"/>
<wire x1="254" y1="-45.72" x2="304.8" y2="-45.72" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_SCL" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="SCL"/>
<pinref part="LCD2" gate="DSI" pin="SCL"/>
<wire x1="254" y1="-50.8" x2="304.8" y2="-50.8" width="0.1524" layer="91"/>
</segment>
</net>
<net name="DSI1_SDA" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="SDA"/>
<pinref part="LCD2" gate="DSI" pin="SDA"/>
<wire x1="254" y1="-53.34" x2="304.8" y2="-53.34" width="0.1524" layer="91"/>
</segment>
</net>
<net name="3V3" class="0">
<segment>
<pinref part="U1" gate="DISP1" pin="3V3"/>
<pinref part="LCD2" gate="DSI" pin="3V3"/>
<wire x1="254" y1="-55.88" x2="304.8" y2="-55.88" width="0.1524" layer="91"/>
</segment>
</net>
<net name="5V" class="0">
<segment>
<pinref part="U1" gate="GPIO" pin="5V@2"/>
<pinref part="LCD2" gate="PWR" pin="5V"/>
<wire x1="289.56" y1="-78.74" x2="340.36" y2="-78.74" width="0.1524" layer="91"/>
</segment>
</net>
<net name="FAN_5V" class="0">
<segment>
<pinref part="U1" gate="FAN" pin="5V"/>
<pinref part="M1" gate="FAN" pin="5V"/>
<wire x1="254" y1="-144.78" x2="304.8" y2="-144.78" width="0.1524" layer="91"/>
</segment>
</net>
<net name="FAN_PWM" class="0">
<segment>
<pinref part="U1" gate="FAN" pin="PWM"/>
<pinref part="M1" gate="FAN" pin="PWM"/>
<wire x1="254" y1="-147.32" x2="304.8" y2="-147.32" width="0.1524" layer="91"/>
</segment>
</net>
<net name="FAN_TACH" class="0">
<segment>
<pinref part="U1" gate="FAN" pin="TACH"/>
<pinref part="M1" gate="FAN" pin="TACH"/>
<wire x1="254" y1="-152.4" x2="304.8" y2="-152.4" width="0.1524" layer="91"/>
</segment>
</net>
</nets>
</sheet>
</sheets>
</schematic>
</drawing>
</eagle>
